### ISSUE TITLE
errors on building

### ISSUE THREAD

**Issue by leillo1975** [PancakeTAS/obs-nvfbc-v30#2]
Hi

I'm trying to build this obs plugin, but when I run "make", I have this error:

`gcc -Wno-unused-parameter -Wall -Wextra -std=gnu17 -Iinclude -fPIC -g -c src/source.c -o src/source.o
src/source.c:6:10: fatal error: xcb/randr.h: Non hai tal ficheiro ou directorio
    6 | #include <xcb/randr.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:19: src/source.o] Error 1`

previously I had to install "libvulkan-dev" to fix a previous bug. It would be good to indicate in the readme the dependencies.

**Comment by PancakeTAS** [comment]
Assuming you are on Arch Linux, you need to install `libxcb`.. which I'm surprised isn't installed already, because practically everything depends on this.

If you're missing any other headers, you can search for the package needed with pacman:
`pacman -F /usr/include/<missing header>`

I'll try to find all the deps needed and put them into the README as well

EDIT: It looks like the only dependency needed on Arch Linux is `mesa`. This would be installed on every system either way, so I'm not going to put anything into the readme.
It looks like you're on debian, so try installing `libxcb1-dev` and similar packages, you might even have to rename the header in the source file.

**Comment by leillo1975** [comment]
I'm on Ubuntu 22.04. I already had libxcb1 and libxcb1-dev installed. I will try to modify the code to fit it to Ubuntu, but I don't have idea on where

**Comment by 0xNULLderef** [comment]
the correct library name for `xcb/randr.h` is `libxcb-randr0-dev`, from my builds it seems it requires something like `sudo apt-get install libobs-dev libegl-dev libgl-dev libvulkan-dev libxcb-randr0-dev`

**Comment by PancakeTAS** [comment]
closing as stale
