### ISSUE TITLE
undefined symbol: NvFBCCreateInstance

### ISSUE THREAD

**Issue by VennStone** [PancakeTAS/obs-nvfbc-v30#3]
Gave this a try on 555.58.02 with the NvFBC patch. Builds clean, links correctly, but OBS errors out with the following. 

`obs: symbol lookup error: /home/venn/.config/obs-studio/plugins/obs-nvfbc/bin/64bit/obs-nvfbc.so: undefined symbol: NvFBCCreateInstance`

This is on Debian 12 / X11 / XFCE using a 3060. 

Could be a case of patch failed successfully  
![Screenshot_2024-07-12_14-19-45](https://github.com/user-attachments/assets/09e76589-f639-4ec6-8b85-95344e2e2ea5)

**Comment by 0xNULLderef** [comment]
few questions for this one to be easier to diagnose
how did you install the driver? i assume since it's a recent version it's probably from the nvidia package from their site-
is the libnvfbc binary in `/usr/lib` or some other path?
what's the output of `readelf --wide -s path_to_libnvfbc.so`?

**Comment by VennStone** [comment]
Right on, thanks for getting back. 

Correct, I installed it using the *.run file as always. 

Everything is installed under `/lib/x86_64-linux-gnu/` but best I can tell, `libnvfbc.so` does not exist on the system. 

I do have symlinks for `libnvidia-fbc.so` pointing to `libnvidia-fbc.so.555.58.02`. Don't know if that's a naming thing or something altogether different?

I included the output of libnvidia-fbc.so for what that's worth. 

[readelfoutput.txt](https://github.com/user-attachments/files/16199446/readelfoutput.txt)

**Comment by 0xNULLderef** [comment]
Somewhat odd, because the Makefile links against your system nvfbc lib, it does seem to load it but it doesn't find the symbol? Your readelf output seems correct, the symbol is correctly exposed and it does match what I have
```
     6: 0000000000011070   239 FUNC    GLOBAL DEFAULT   12 NvFBCCreateInstance
```
You can try launching OBS with an overridden linker load path, like `LD_LIBRARY_PATH=/lib/x86_64-linux-gnu obs`, however it does seem to be in the default location and it wouldn't make sense for the library not to be in the search path... I will try to replicate today and get back if i find more
